ci: use github provided auto-merge behavior for flake update

diff --git a/.github/workflows/cachix.yml b/.github/workflows/cachix.yml
--- a/.github/workflows/cachix.yml
+++ b/.github/workflows/cachix.yml
@@ -72,3 +72,16 @@ jobs:
             --print-build-logs \
             --fallback \
             --system ${{ matrix.system }}
+
+  all_builds:
+    name: All builds passed
+    runs-on: ubuntu-latest
+    needs: [build]
+    if: always()
+    steps:
+      - name: Check matrix results
+        run: |
+          if [ "${{ needs.build.result }}" != "success" ]; then
+            echo "One or more builds failed"
+            exit 1
+          fi
